markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
theme: jekyll-theme-slate
title: Trobotix 8696 GitHub
description: Trobotix FTC source code.